version: '3'
 
services:
  arma:
    build: 
      context: ./autre/arma
      dockerfile: Dockerfile
    image: stargate:arma
    container_name: arma-${INSTANCE_NAME}
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${SERVER_PORT}:${SERVER_PORT}/udp"
    volumes:
      - ./build/server:/server:rw
      - /server/@extDB3/logs
    entrypoint: /bin/sh -c
    command: 
      - |
        cd /server
        sh run.sh
    depends_on:
      - mysql

  mysql:
    build: 
      context: ./autre/database
      dockerfile: Dockerfile
    image: stargate:mysql
    container_name: mysql-${INSTANCE_NAME}
    environment:
      MARIADB_ROOT_PASSWORD: ${BDD_ROOT_PASSWORD}
      MARIADB_DATABASE: ${BDD_DATABASE}
      MARIADB_USER: ${BDD_USERNAME}
      MARIADB_PASSWORD: ${BDD_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    depends_on:
      - phpmyadmin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    container_name: phpmyadmin-${INSTANCE_NAME}
    environment:
      PMA_HOST: mysql-${INSTANCE_NAME}
      PMA_PORT: 3306
    restart: always
    ports:
      - "${PMA_PORT}:80"

volumes:
  mysql:
    name: ${INSTANCE_NAME}-mysql