services:
  arma:
    image: arma:latest
    restart: always
    environment:
      STEAM_USER: aureprod
      STEAM_PASSWORD: XJKDsqDXnfy7wHtphx4xV6xR2CyVRp
      ADMIN_PASSWORD: JCpLNmNvyZVTQHwVcsOVscpgLxT0n7
      ARMA_PARAMS: -autoinit
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: stargate
      MYSQL_USER: superadmin
      MYSQL_PASSWORD: pivOg1HULmj04zbnb0qXURmT0c9Oci
    ports:
      - 2302-2306:2302-2306/udp
    volumes:
      - ./build:/server
      - ./mission.Stargate_Impact_Map:/configs/mpmissions/mission.Stargate_Impact_Map
      - ./@mod_server:/configs/servermods/@mod_server
      - ./configs/mods.json:/configs/mods.json
      - ./configs/server.cfg:/configs/server.cfg
    depends_on:
      - db
    networks:
      - default

  db:
    image: mariadb:10.3.35
    restart: always
    volumes:
      - db:/var/lib/mysql
      - ./configs/database.sql:/docker-entrypoint-initdb.d/database.sql
    environment:
      MYSQL_ROOT_PASSWORD: KMybsPjyV4Cqx1VWLJZLWPS2cvS9bX
      MYSQL_DATABASE: stargate
      MYSQL_USER: superadmin
      MYSQL_PASSWORD: pivOg1HULmj04zbnb0qXURmT0c9Oci
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      TZ: Europe/Paris
      PMA_HOST: db
      PMA_PORT: 3306
    restart: always
    depends_on:
      - db
    networks:
      - default
    ports:
      - "8045:80"

volumes:
  db:

networks:
  default: